from django.conf.urls.defaults import *

urlpatterns = patterns('kapai_django.index.views',
	(r'^faq.php', 'forum_redir'),
	(r'^index.php', 'forum_redir'),
	(r'^memberlist.php', 'forum_redir'),
	(r'^mcp.php', 'forum_redir'),
	(r'^posting.php', 'forum_redir'),
	(r'^report.php', 'forum_redir'),
	(r'^search.php', 'forum_redir'),
	(r'^style.php', 'forum_redir'),
	(r'^ucp.php', 'forum_redir'),
	(r'^viewforum.php', 'forum_redir'),
	(r'^viewtopic.php', 'forum_redir'),
	(r'^viewonline.php', 'forum_redir'),
	(r'^adm/', 'forum_redir'),
	(r'^cache', 'forum_redir'),
	(r'^download', 'forum_redir'),
	(r'^files', 'forum_redir'),
	(r'^images', 'forum_redir'),
	(r'^includes', 'forum_redir'),
	(r'^language', 'forum_redir'),
	(r'^store', 'forum_redir'),
	(r'^styles', 'forum_redir'),
	(r'^wowhead', 'forum_redir'),
	(r'^apply$', 'redirect'),
	(r'^apply/$', 'redirect'),
	(r'^guide$', 'redirect'),
	(r'^guide/$', 'redirect'),
	(r'^charter$', 'redirect'),
	(r'^charter/$', 'redirect'),
	(r'^$', 'index'),
)
